# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(default='03/02/2014', max_length=255),
        ),
    ]
